Merge bug Fixes
OpenVSLAM-Community/openvslam pull request #139
Opened 2021-08-04 15:05 UTC by jeffin07

Fixed the remaining task in #3 

1. Fix warning by removing redundant std::move() 
2. Added double quotes around BUILD_INTERFACE and INSTALL_INTERFACE

2021-08-04 15:29 UTC, jeffin07 commented
I changed a file in submodule `3rd/FBoW/CMakeLists.txt` but i 'm not able to commit that file. Any suggestions?

2021-08-04 22:43 UTC, ymd-stella requested changes

2021-08-04 22:43 UTC, ymd-stella commented on src/openvslam/CMakeLists.txt
> +                           "$<INSTALL_INTERFACE:include/>")
```suggestion
                           "$<BUILD_INTERFACE:${json_INCLUDE_DIR}>"
                           "$<BUILD_INTERFACE:${spdlog_INCLUDE_DIR}>"
                           "$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/src/>"
                           "$<INSTALL_INTERFACE:include/openvslam/3rd/json/include>"
                           "$<INSTALL_INTERFACE:include/openvslam/3rd/spdlog/include>"
                           "$<INSTALL_INTERFACE:include/>")
```

2021-08-06 00:41 UTC, ymd-stella commented
Please submit a pull request to https://github.com/OpenVSLAM-Community/FBoW for b1acfd8a898b6dbe9387ae2bc25d6f27e54c7234. FBoW is a submodule.

2021-08-06 00:41 UTC, ymd-stella commented
@jeffin07 Please submit a pull request to https://github.com/OpenVSLAM-Community/FBoW for b1acfd8. FBoW is a submodule.

2021-08-06 13:47 UTC, jeffin07 commented
@ymd-stella  so do i need to  undo the current changes in FBoW

2021-08-06 14:14 UTC, ymd-stella commented
Use f427af71e1362cea1f35c7914136fee4d0d02adc.

2021-08-06 14:26 UTC, jeffin07 commented
@ymd-stella I'm sorry i didn't get that . Could you please explain.sorry I'm new to submodule.

2021-08-06 14:34 UTC, ymd-stella commented
Stage the changes as follows:

```bash
cd 3rd/FBoW
git fetch
git reset --hard origin/master
cd ..
git add FBoW
```

2021-08-06 14:40 UTC, ymd-stella commented
It doesn't seem to have changed.

2021-08-06 15:18 UTC, merged